# Generated by Django 5.0 on 2023-12-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora', models.DateTimeField()),
                ('accion', models.CharField(choices=[('dar_comida', 'Alimentar'), ('dar_agua', 'Aguita')], max_length=20)),
                ('ejecutado', models.BooleanField(default=False)),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
                ('minuto', models.IntegerField()),
            ],
        ),
    ]
