# Generated by Django 5.0 on 2024-01-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comando', '0002_peticion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Peticion',
        ),
    ]
